// Generated by scripts/generate-image-blur.mjs — do not edit by hand.
/**
 * Low-quality image placeholders, keyed by the same `src` path passed to
 * <Image />. Each is a 12px-wide WebP inlined as a data URI (a few hundred
 * bytes). Without one, a photo on a cream or white section paints as an empty
 * rectangle until it decodes.
 */
export const IMAGE_BLUR: Readonly<Record<string, string>> = {
  '/images/abishan-avatar.webp':
    'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoMAAwAA8BgJYwCdAYtLuV9+9Eg3YAA/vCvlX5x8puTI8/jwkOw2vAVPntQtfs0GrZ0eoyYNq8MMu7bP7uK2xh54TE7fsYF1r6QE1dAoWvjb1TlWsYGwADQAAA=',
  '/images/abishan.webp':
    'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoIAAwAA8BgJZwAAp2jzWwAAP7ybLIr1vyPjbw9HprkDbY5Nwcf+TJnhfgZAxRRMXaAyuBBh5EG/CgAAAA=',
  '/images/homelife-award.jpg':
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAAgAA8BgJaQAAiGfosiAAP70sPLGGJ3oAPjUfcKDgvZ9lrakxMgqdr/zKhOuS9Yl0AAA',
  '/images/modern-living-room.jpg':
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAgAA8BgJYgC7AEO6qvi7RAA/ufezYdYPUzwMucHaQCa9tO+fcROVEXz2pgkx8LhwgAA',
  '/images/neighbourhood.jpg':
    'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAcAA8BgJZACw7ELM/CvhoAA9pCVD3aSprzyN8djjawZZE2CSnFqHawoG+h2vFn4cJUg2nrl6eAA',
  '/images/pexels-19836798.jpg':
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoIAAwAA8BgJQBOgB6Q6DigAAD+xydI2ObEP99iDcZHAx2cTZt22BVSW+1qXgZA2Z8JMgAA',
  '/images/pexels-2478248.jpg':
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAgAA8BgJQBOgCFsDZi8AAD+8X8fO9DLo1fzko4Xk2/Snp9RpDvXBCGC+QtYo/vpe4AA',
  '/images/pexels-31651009.jpg':
    'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAgAA8BgJZgCdAC9Kztg+AAA/Mw4w/5AcQh2hMy9d3cSjxNPv5tYWPR/oD0altfWZuxBzEQgAA==',
  '/images/pexels-5071177.jpg':
    'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMAAkAA8BgJYgCdEf/gfOG3AAA/N+xjRSfRtjWH8vDxC9MWyXNEfxV9eft5GITJ7mLyfw1ZJ7tWE/28zEj+xnD0RTiUZYAAAA=',
  '/images/toronto-skyline.jpg':
    'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAAgAA8BgJQBOgCHoTnjwAP5mjQClB50LhQ4OTKunsYtBwQyZU/2eR/aNCFv5KP+pQwAA',
}

/** The placeholder for a src, or undefined if none was generated. */
export function blurFor(src: string): string | undefined {
  return IMAGE_BLUR[src]
}
